google_user = "username@gmail.com"
google_password = "password"
meteor_db_name = "meteor"
meteor_mongo_port = 3001
fields_spreadsheet_id = "abcd"
events_spreadsheet_id = "abcd"
zotero_library_id = '1234'
zotero_library_type='group'
zotero_api_key = 'abcd'
